---
env:
  browser: true
extends: airbnb
parser: babel-eslint
rules:
  function-paren-newline: 0
  global-require: 0
  # graphql/template-strings:
  #   - error
  #   - env: literal
  indent: 0
  no-underscore-dangle: 0
  no-plusplus: 0
  no-multi-assign: 0
  no-nested-ternary: 0
  react/destructuring-assignment: never
  prefer-destructuring: 0
  enforceForRenamedProperties: false
  requireForBlockBody: true
  no-unneeded-ternary: 0
  no-param-reassign: 0
  ignoreArrayIndexes: false
  no-unused-expressions:
    - error
    - allowShortCircuit: true
  max-len:
    - error
    - ignoreComments: true
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: ignore
  react/prop-types: 0
  react/sort-comp: 0
  react/no-multi-comp: 0
  jsx-a11y/no-static-element-interactions: 0
  jsx-a11y/no-noninteractive-element-interactions: 0
  react/jsx-filename-extension:
    - error
    - extensions:
      - .js
      - .jsx
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
      peerDependencies: true
  no-await-in-loop: 0
